//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCMovies18.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; // Need to add to turn on validation
    
    public partial class Movie
    {
        public int Id { get; set; }

        [Required] // Needed to add data validation to NOT NULL fields so that the code will not proceed without input in this field
        [StringLength(60, MinimumLength = 2)] // Max/Min length for data input
        public string Title { get; set; }

        [Display(Name = "Release Date")] // Changes the label for the data to something other than the db column heading
        [DataType(DataType.Date)] // Displays data as date only rather than date/time
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}", ApplyFormatInEditMode = true)] 
        // Changes the display format of the date, works in IE & FF, not Chrome or edge
        public Nullable<System.DateTime> ReleaseDate { get; set; }

        [Required]
        [StringLength(30)] 
        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s\-]*$", ErrorMessage = "Genre must begin with a capital letter")]
        // Regular expression checks pattern of text like e-mail addresses
        // The pattern here is to start with a capital then have 0 or > letters, spaces, hyphens or apostraphes
        // ErrorMessage will change the displayed error message by the Html.ValidationSummary() to entered text from the default
        // (In this case the default includes @"^[A-Z]+[a-zA-Z''-'\s\-]*$" which a user will not understand
        public string Genre { get; set; }

        [Range(0,1000)] // Sets range of any numerical value
        [DataType(DataType.Currency)] // Displays a currency symbol. Set culture in web.config to change the currency symbol
        public Nullable<decimal> Price { get; set; }

        public string ImageUrl { get; set; }
    }
}
