//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLEntityDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string orderLine1 { get; set; }
        public string orderLine2 { get; set; }
        public Nullable<decimal> total { get; set; }
        public int customerid { get; set; }
    }
}
